### PR TITLE
Migrate Node Network Functionality to esisdk

### PR DESCRIPTION
**Pull request by ajamias**
This commit is to reflect the changes to move the
network attach functionality to esisdk. This is so that both python-esiclient and esi-ui can use this functionality.

### CODE REVIEW

**Review by tzumainn — CHANGES_REQUESTED** [review]
Don't forget to update the esisdk version in requirements.txt!

**Review by tzumainn — APPROVED** [review]
Looks good! Feel free to take this out of draft, and I'll merge.

**Comment by ajamias** [comment]
Should we take python<=3.7 tests out? The tests are giving an error

**Comment by tzumainn** [comment]
Yeah, I submitted a PR for that!

**Pull request merged**
